version: "3.8"

services:
  node:
    image: wakscode-node
    build: .
    command: python app/main.py
    restart: always
    volumes:
      - type: bind
        source: .env
        target: /code/.env
