name: Docker Image Build and Swarm Deploy
on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: minibox24/wakscord-node:latest
  SERVICE_NAME: wakscord-node
  CONTAINER_REPLICA_COUNT: 10

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://${{ secrets.MANAGER_USERNAME }}@${{ secrets.MANAGER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: service update --replicas ${{ env.CONTAINER_REPLICA_COUNT }} --image ${{ env.DOCKER_IMAGE }} ${{ env.SERVICE_NAME }}